### PR TITLE
fixed Slack support

### LINKED ISSUE #5: Fix sending of help DM

### PR DESCRIPTION
**Pull request by naterchrdsn**
resolves #5, #1, #4

### CODE REVIEW

File: lib/onEvent/message.js [hunk 1]
```diff
@@ -2,35 +2,81 @@ const Kirbi = require('../../../../kirbi');
...
+
 function slackMessageCb (output, msg, expires, delCalling) {
 	//we need to format the message output for the Slack API first...
-	let reformatted = {};
+	if (typeof output === 'object') {
+		let reformatted;
+		reformatted = {};
+		reformatted.attachments = [];
+		reformatted.attachments[0] = {};
+		reformatted.attachments[0].fallback = 'There was an error';
```
Comment (Morandustries) [inline lib/onEvent/message.js]: Change this whole part to just be 
```
let reformatted = {
    attachments: [
        { fallback: 'There was an error' }
    ]
};
```

File: lib/onEvent/message.js [hunk 2]
```diff
@@ -2,35 +2,81 @@ const Kirbi = require('../../../../kirbi');
...
+		if (output.embed.color) reformatted.attachments[0].color = `#${output.embed.color}`;
+		if (output.embed.title) reformatted.attachments[0].title = output.embed.title;
+		if (output.embed.description) reformatted.attachments[0].text = output.embed.description;
+		if (typeof output.embed.image !== 'undefined') reformatted.attachments[0].image_url = output.embed.image.url;
```
Comment (Morandustries) [inline lib/onEvent/message.js]: if you're going to check type, check for object not `!== 'undefined'`

File: lib/onEvent/message.js [hunk 3]
```diff
@@ -2,35 +2,81 @@ const Kirbi = require('../../../../kirbi');
...
+		if (typeof output.embed.thumbnail !== 'undefined') reformatted.attachments[0].thumb_url = output.embed.thumbnail.url;
+		if (output.embed.footer) reformatted.attachments[0].footer = output.embed.footer;
```
Comment (Morandustries) [inline lib/onEvent/message.js]: I'd group all the attributes that aren't being changed together after you first make the attachment.

File: lib/onEvent/message.js (hunk 2 above)
Comment (Morandustries) [reply lib/onEvent/message.js]: This applies to thumbnail and author

File: lib/onEvent/message.js [hunk 4]
```diff
@@ -40,34 +86,38 @@ function checkMessageForCommand (msg, isEdit) {
 	if (isMention(msg.text.split(' '))) {
```
Comment (Morandustries) [inline lib/onEvent/message.js]: why aren't we just doing the check? I dont see the need for an internal function.

File: lib/onEvent/message.js [hunk 5]
```diff
@@ -40,34 +86,38 @@ function checkMessageForCommand (msg, isEdit) {
...
 		if (Kirbi.Config.elizaEnabled) {
 			//If Eliza AI is enabled, respond to @mention
-			var message = msg.text.replace(`<@${Kirbi.Slack._self.id}> `, '');
+			let message = msg.text.replace(`<@${self.id}> `, '');
```
Comment (Morandustries) [inline lib/onEvent/message.js]: const not let.

File: lib/onEvent/message.js [hunk 6]
```diff
@@ -40,34 +86,38 @@ function checkMessageForCommand (msg, isEdit) {
...
 			Kirbi.Slack.sendMessage(Kirbi.Eliza.transform(message), msg.channel);
+			return;
 		} else {
 			Kirbi.Slack.sendMessage('Yes?', msg.channel);
 			return;
 		};
 	};
+	//check for IM
+	if (typeof Kirbi.Slack.dataStore.getDMById(msg.channel) !== 'undefined') {
```
Comment (Morandustries) [inline lib/onEvent/message.js]: no need for type check because undefined values return false

File: lib/onEvent/message.js [hunk 7]
```diff
@@ -40,34 +86,38 @@ function checkMessageForCommand (msg, isEdit) {
...
 	if (msg.text.startsWith(Kirbi.Config.commandPrefix)) {
 		let allCommands = Object.assign(Kirbi.Commands, Kirbi.slackCommands);
-		var cmdTxt = msg.text.split(' ')[0].substring(Kirbi.Config.commandPrefix.length).toLowerCase();
-		var suffix = msg.text.substring(cmdTxt.length + Kirbi.Config.commandPrefix.length + 1); //add one for the ! and one for the space
-		var cmd = allCommands[cmdTxt];
-		if (msg.type === "dm") {
-			Kirbi.Slack.sendMessage(`I don't respond to direct messages.`, msg.channel);
-		} else if (cmdTxt === 'help') {
-			//help is special since it iterates over the other commands
+		let cmdTxt = msg.text.split(' ')[0].substring(Kirbi.Config.commandPrefix.length).toLowerCase();
```
Comment (Morandustries) [inline lib/onEvent/message.js]: let to const

File: lib/onEvent/message.js [hunk 8]
```diff
@@ -40,34 +86,38 @@ function checkMessageForCommand (msg, isEdit) {
...
+		let suffix = msg.text.substring(cmdTxt.length + Kirbi.Config.commandPrefix.length + 1); //add one for the ! and one for the space
```
Comment (Morandustries) [inline lib/onEvent/message.js]: const

File: lib/onEvent/message.js [hunk 9]
```diff
@@ -40,34 +86,38 @@ function checkMessageForCommand (msg, isEdit) {
...
+		let cmd = allCommands[cmdTxt];
+		if (cmdTxt === 'help') {
+			let DM = Kirbi.Slack.dataStore.getDMByUserId(msg.user).id;
 			if (suffix) {
-				var cmds = suffix.split(' ').filter(function (cmd) { return allCommands[cmd] });
-				var info = "";
+				let cmds = suffix.split(' ').filter(function (cmd) { return allCommands[cmd] });
```
Comment (Morandustries) [inline lib/onEvent/message.js:109]: filter will do a loop, why not make it a forEach and build the info rather than looping through all commands twice?

File: lib/onEvent/message.js [hunk 10]
```diff
@@ -76,35 +126,35 @@ function checkMessageForCommand (msg, isEdit) {
...
-				Kirbi.Slack.sendMessage('**Available Commands:**', msg.user);
-				var batch = '';
-				var sortedCommands = Object.keys(allCommands).sort();
-				for (var i in sortedCommands) {
-					var cmd = sortedCommands[i];
-					var info = `**${Kirbi.Config.commandPrefix + cmd}**`;
-					var usage = allCommands[cmd].usage;
+				Kirbi.Slack.sendMessage('**Available Commands:**', DM);
+				let batch = '';
+				let sortedCommands = Object.keys(allCommands).sort();
```
Comment (Morandustries) [inline lib/onEvent/message.js]: const

File: lib/onEvent/message.js [hunk 11]
```diff
@@ -76,35 +126,35 @@ function checkMessageForCommand (msg, isEdit) {
...
+				for (let i in sortedCommands) {
+					let cmd = sortedCommands[i];
+					let info = `**${Kirbi.Config.commandPrefix + cmd}**`;
+					let usage = allCommands[cmd].usage;
```
Comment (Morandustries) [inline lib/onEvent/message.js]: const

File: lib/onEvent/message.js [hunk 12]
```diff
@@ -76,35 +126,35 @@ function checkMessageForCommand (msg, isEdit) {
...
-					var description = allCommands[cmd].description;
+					let description = allCommands[cmd].description;
 					if (description instanceof Function) {
 						description = description();
 					}
 					if (description) {
 						info += `\n\t${description}`;
 					}
-					var newBatch = `${batch}\n${info}`;
+					let newBatch = `${batch}\n${info}`;
```
Comment (Morandustries) [inline lib/onEvent/message.js]: const

File: lib/onEvent/message.js [hunk 13]
```diff
@@ -113,16 +163,16 @@ function checkMessageForCommand (msg, isEdit) {
...
 		} else {
-			Kirbi.Slack.sendMessage(`${cmdTxt} not recognized as a command!`);
+			Kirbi.Slack.sendMessage(`${cmdTxt} not recognized as a command!`, msg.channel);
 		}
 	};
 };
 
-Kirbi.Slack.on(Kirbi.Slack.rtm_events.MESSAGE, (msg) => checkMessageForCommand(msg, false));
\ No newline at end of file
+Kirbi.Slack.on(Kirbi.Slack.rtm_events.MESSAGE, (msg) => checkMessageForCommand(msg, false));
```
Comment (Morandustries) [inline lib/onEvent/message.js]: no need for parenthesis

File: slackSupport.js [hunk 14]
```diff
@@ -6,15 +6,19 @@ exports.slackLogin = function () {
 	console.log(chalk.magenta(`Slack Enabled... Starting.`));
 	if (Kirbi.Auth.slack.bot_token) {
 		console.log('Logging in to Slack...');
-        Kirbi.Slack = new RtmClient(Kirbi.Auth.slack.bot_token);
+		let MemoryDataStore = require('@slack/client').MemoryDataStore;
+        Kirbi.Slack = new RtmClient(Kirbi.Auth.slack.bot_token, {
```
Comment (Morandustries) [inline slackSupport.js:10]: spacing

File: slackSupport.js [hunk 15]
```diff
@@ -6,15 +6,19 @@ exports.slackLogin = function () {
...
+		});
 		Kirbi.Slack.c_events = require('@slack/client').CLIENT_EVENTS;
 		Kirbi.Slack.rtm_events = require('@slack/client').RTM_EVENTS;
         Kirbi.Slack.start();
 		require('./lib/onEvent');
 	} else {
         console.log(chalk.red('ERROR: Kirbi must have a Slack bot token...'));
         return;
-	};
+	}
```
Comment (Morandustries) [inline slackSupport.js]: your doing a value assignment, I would keep the ; 

I don't know if we talked about this but I prefer ; after every statement for clarity.

File: lib/onEvent/message.js [hunk 16]
```diff
@@ -2,35 +2,81 @@ const Kirbi = require('../../../../kirbi');
...
+	//	return msg.channel.send(output).then(message => message.delete(5000));
+	//}
+	//if (delCalling) {
+	//	return msg.channel.send(output).then(() => msg.delete());
+	//}
 	Kirbi.Slack.sendMessage(output, msg.channel);
 };
 
 function checkMessageForCommand (msg, isEdit) {
+	let self = Kirbi.Slack.dataStore.getBotByName('Kirbi');
```
Comment (Morandustries) [inline lib/onEvent/message.js]: this should be const since the value doesnt change.

File: lib/onEvent/message.js [hunk 17]
```diff
@@ -2,35 +2,81 @@ const Kirbi = require('../../../../kirbi');
...
 
 
 	//then send it and interact with it based on the supplied flags...
-	if (expires) {
-		return msg.channel.send(output).then(message => message.delete(5000));
-	}
-	if (delCalling) {
-		return msg.channel.send(output).then(() => msg.delete());
-	}
+	//if (expires) {
```
Comment (Morandustries) [inline lib/onEvent/message.js:64]: delete if not being used.

File: lib/onEvent/message.js (hunk 1 above)
Comment (Morandustries) [reply lib/onEvent/message.js]: also since the actual assignment isn't being changed, this should be a const instead of a let

**Review by Morandustries — CHANGES_REQUESTED** [review]
Mostly minor fixes.

One thing to note is understanding when to use let vs const. If a value is not going to be reassigned (such as assigning an object which will only have its properties redefined or a basic data type) use const. We might want to get a js linter that will ensure we are following a style guideline.

File: lib/onEvent/message.js (hunk 3 above)
Comment (naterchrdsn) [reply lib/onEvent/message.js]: they aren't present in all, I'll just leave the check in

File: lib/onEvent/message.js (hunk 17 above)
Comment (naterchrdsn) [reply lib/onEvent/message.js:64]: leaving in since it needs to be fixed in the future. I'll add a TODO

File: lib/onEvent/message.js (hunk 9 above)
Comment (naterchrdsn) [reply lib/onEvent/message.js:109]: the filter makes sure that the supplied arguments are actually commands.

then we take the list and work through it

Comment (Morandustries) [reply lib/onEvent/message.js:109]: or we can just do a foreach, see if it is a command and if so do it. This way we are only looping once. That being said its a microoptimization, I wouldn't say its blocking it. We can leave it and optimize it at a later date.

**Review by Morandustries — APPROVED** [review]
